FROM node:20-alpine

# Set working directory
WORKDIR /var/www/html

# Copy the application files
COPY ./app /var/www/html

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 5173

# Start the application
CMD ["npm", "run", "dev"]